<?php $this->display('common/head');?>
<body>
<div class="article">


    <div class="content">


        <?php echo $total;?>
    </div>

</div>
</body>
<script  type="application/javascript" src="/erick/public/socket/socket.io.js"></script>
<script>

    var wsl= 'ws://127.0.0.1:9502';
ws = new WebSocket(wsl);//新建立一个连接
//如下指定事件处理 
ws.onopen = function(){ws.send('Test!'); };  
ws.onmessage = function(evt){console.log(evt.data);/*ws.close();*/};  
ws.onclose = function(evt){console.log('WebSocketClosed!');};  
ws.onerror = function(evt){console.log('WebSocketError!');}; 
     </script>
<?php $this->display('common/footer');?>
</html>